apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: todoapp-servicemonitor
  labels:
    release: kube-prometheus-stack
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  endpoints:
    - port: http
      path: /metrics
      interval: 10s